# Pre-commit hooks for pyFIA - simplified configuration
# See https://pre-commit.com for more information

default_language_version:
  python: python3.11

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python code formatting with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi]
      # Run the linter
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --exit-non-zero-on-fix]

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          - polars>=1.31.0
          - numpy>=2.3.0
          - pydantic>=2.0.0
        args: [--config-file=pyproject.toml]
        files: ^src/pyfia/
        pass_filenames: false

# Configuration for specific hooks
files: ^(src/pyfia/|tests/|docs/)
exclude: ^(\.git/|\.mypy_cache/|\.pytest_cache/|\.ruff_cache/|build/|dist/|.*\.egg-info/|htmlcov/)