[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfia"
version = "0.3.0"
description = "High-performance Python library for Forest Inventory Analysis (FIA) data analysis"
readme = "README.md"
authors = [
    {name = "Chris Mihiar", email = "28452317+mihiarc@users.noreply.github.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11"
dependencies = [
    "polars>=1.31.0",
    "numpy>=2.3.0",
    "connectorx>=0.3.1",
    "duckdb>=0.9.0",
    "pyarrow>=14.0.0",
    "pydantic>=2.11.0",
    "pydantic-settings>=2.7.0",
    "rich",
    "pyyaml>=6.0.0",
    "pandas>=2.3.1",
]

[project.optional-dependencies]
spatial = ["geopandas>=1.1.0", "shapely>=2.1.1"]
pandas = ["pandas>=2.3.0"]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.0",
    "mypy>=1.16.1",
    "hypothesis>=6.130.0",
    "hypothesis[numpy]>=6.130.0",
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "pre-commit>=3.6.0",
]
all = ["pyfia[spatial,pandas,dev]"]

[project.urls]
Homepage = "https://github.com/mihiarc/pyfia"
Documentation = "https://github.com/mihiarc/pyfia"
Repository = "https://github.com/mihiarc/pyfia"
Issues = "https://github.com/mihiarc/pyfia/issues"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyfia*"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]
ignore = [
    "E501",  # line too long
    "N803",  # argument name should be lowercase (keeping R/FIA conventions)
    "N815",  # mixed case variable in class scope (keeping R/FIA conventions)
    "E722",  # bare except
    "E402",  # module import not at top
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.11"
# Basic settings - not overly strict
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
show_column_numbers = true
pretty = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]
python_classes = ["Test*"]

[dependency-groups]
dev = [
    # hypothesis already declared in [project.optional-dependencies].dev
]
