<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Hunter Stanke, Jeffrey W. Doser" />


<title>FIA Demystified</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">FIA Demystified</h1>
<h4 class="author">Hunter Stanke, Jeffrey W. Doser</h4>
<h4 class="date">2020 (last updated February 7, 2025)</h4>


<div id="TOC">
<ul>
<li><a href="#estimation-at-the-plot-level" id="toc-estimation-at-the-plot-level">Estimation at the plot-level</a>
<ul>
<li><a href="#two-example-plots" id="toc-two-example-plots">Two example
plots</a></li>
<li><a href="#basic-estimation-procedures" id="toc-basic-estimation-procedures">Basic Estimation
Procedures</a></li>
<li><a href="#unique-domains-of-interest" id="toc-unique-domains-of-interest">Unique domains of interest</a></li>
<li><a href="#grouped-estimation-procedures" id="toc-grouped-estimation-procedures">Grouped estimation
procedures</a></li>
</ul></li>
<li><a href="#estimation-at-the-population-level" id="toc-estimation-at-the-population-level">Estimation at the
population-level</a>
<ul>
<li><a href="#data-preparation" id="toc-data-preparation">Data
Preparation</a></li>
<li><a href="#without-sampling-errors" id="toc-without-sampling-errors">Without Sampling Errors</a>
<ul>
<li><a href="#no-grouping-variables" id="toc-no-grouping-variables">No
grouping variables</a></li>
<li><a href="#adding-grouping-variables" id="toc-adding-grouping-variables">Adding grouping variables</a></li>
</ul></li>
<li><a href="#with-sampling-errors" id="toc-with-sampling-errors">With
Sampling Errors</a>
<ul>
<li><a href="#no-grouping-variables-1" id="toc-no-grouping-variables-1">No grouping variables</a></li>
<li><a href="#adding-grouping-variables-1" id="toc-adding-grouping-variables-1">Adding grouping variables</a></li>
</ul></li>
</ul></li>
</ul>
</div>

<p>Despite being publicly available, FIA data are notoriosly difficult
for most non-FIA users to interpret and understand, and there is
potential to greatly increase the utilization of these data among
industry professionals, academic scientists, and the general public. We
created <code>rFIA</code> to solve this problem, offering a flexible,
user-friendly tool which simplifies the process of working with FIA data
and helps ensure this valuable public resource is, well… public.</p>
<p>In the examples that follow, we will show you the methods that
underpin the estimation capacity of <code>rFIA</code>. We do not attempt
to expain every line of code in the <code>rFIA</code> package here, but
rather we present a simplified version to highlight our implementation
of the major estimation procedures. You can find the complete source
code for rFIA at <a href="https://github.com/doserjef/rFIA">the
development repository</a>.</p>
<div id="estimation-at-the-plot-level" class="section level1">
<h1>Estimation at the plot-level</h1>
<p>In the examples below, we highlight the basic estimation procedures
used to compute plot-level estimates of forest attributes from Forest
Inventory and Analysis (FIA) data. We will demonstrate these procedures
for two plots contained in the <code>fiaRI</code> dataset (included in
the <code>rFIA</code> package) so that you can follow along with a small
dataset.</p>
<p>The source code for <code>rFIA</code> will vary slightly from that
presented below as we designed <code>rFIA</code> to be as flexible and
computationally efficient as possible. Despite the differences in syntax
and structure, the estimation procedures presented below are identical
to those in <code>rFIA</code>.</p>
<div id="two-example-plots" class="section level2">
<h2>Two example plots</h2>
<p>First, let’s load some packages and the <code>fiaRI</code>
dataset:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># Load some packages</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(rFIA)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="co"># Load the fiaRI dataset (included in rFIA)</span></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">data</span>(fiaRI)</span></code></pre></div>
<p>To compute estimates of tree biomass/carbon at the plot-level, we
really only need the tree, condition, and plot tables. In the code
below, we will subset the rows of these tables which pertain to our two
plots of interest (<code>a</code> &amp; <code>b</code> below):</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="co"># Some unique identifiers for two plots in fiaRI database object</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="co"># For example use below, both measured in 2014</span></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">168263223020004</span>  <span class="co"># One forested condition</span></span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">168263219020004</span>  <span class="co"># Two forested, one non-forested condition</span></span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a><span class="co"># Subset the PLOT, COND, and TREE tables for plot A</span></span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a>plot_a <span class="ot">&lt;-</span> <span class="fu">filter</span>(fiaRI<span class="sc">$</span>PLOT, CN <span class="sc">==</span> a)</span>
<span id="cb2-8"><a href="#cb2-8" tabindex="-1"></a>cond_a <span class="ot">&lt;-</span> <span class="fu">filter</span>(fiaRI<span class="sc">$</span>COND, PLT_CN <span class="sc">==</span> a)</span>
<span id="cb2-9"><a href="#cb2-9" tabindex="-1"></a>tree_a <span class="ot">&lt;-</span> <span class="fu">filter</span>(fiaRI<span class="sc">$</span>TREE, PLT_CN <span class="sc">==</span> a)</span>
<span id="cb2-10"><a href="#cb2-10" tabindex="-1"></a><span class="co"># Subset the PLOT, COND, and TREE tables for plot B</span></span>
<span id="cb2-11"><a href="#cb2-11" tabindex="-1"></a>plot_b <span class="ot">&lt;-</span> <span class="fu">filter</span>(fiaRI<span class="sc">$</span>PLOT, CN <span class="sc">==</span> b)</span>
<span id="cb2-12"><a href="#cb2-12" tabindex="-1"></a>cond_b <span class="ot">&lt;-</span> <span class="fu">filter</span>(fiaRI<span class="sc">$</span>COND, PLT_CN <span class="sc">==</span> b)</span>
<span id="cb2-13"><a href="#cb2-13" tabindex="-1"></a>tree_b <span class="ot">&lt;-</span> <span class="fu">filter</span>(fiaRI<span class="sc">$</span>TREE, PLT_CN <span class="sc">==</span> b)</span></code></pre></div>
<p>Now that we have the tables we need for our plots of interest, let’s
take a look at their <code>COND</code> tables and see how these plots
are different:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># COND_STATUS_CD indicates the basic land classification of a</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="co"># condition, whether it is forested, non-forest, water, etc...</span></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a><span class="co"># COND_STATUS_CD = 1 indicates forested</span></span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>cond_a<span class="sc">$</span>COND_STATUS_CD <span class="co"># One forested condition</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>cond_b<span class="sc">$</span>COND_STATUS_CD <span class="co"># Two forested, and one non-forest</span></span></code></pre></div>
<pre><code>## [1] 1 1 2</code></pre>
<p>The <code>COND</code> table lists the conditions, or land classes
present on an FIA plot. Conditions may be obvious, such as when a plot
intersects a forest edge (the forested area and non-forested area would
be seperate conditions). However, more subtle differences between
forested area on a plot, such as differences in reserved status, owner
group, forest type, stand-size class, regeneration status, and stand
density can further define conditions.</p>
<p>Since there are two forested conditions on Plot B, what is the basis
for the distinction?</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># FORTYPCD indicates the forest type of the condition</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a><span class="co"># PHYSCLCD indicates the Physiographic class (e.g. mesic moist slope)</span></span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>cond_b<span class="sc">$</span>FORTYPCD</span></code></pre></div>
<pre><code>## [1] 505 708  NA</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>cond_b<span class="sc">$</span>PHYSCLCD</span></code></pre></div>
<pre><code>## [1] 21 31 NA</code></pre>
<p>Looks like we have one forested condition in the Northern red oak
forest type (<code>FORTYPCD = 505</code>) occuring on mesic flatwoods
(<code>PHYSCLCD = 21</code>), and a second forested condition in the Red
maple/lowland forest type (<code>FORTYPCD = 708</code>) on a hydric
swamp/bog (<code>PHYSCLCD = 31</code>). The <code>NA</code> values
relate to the non-forested condition on the plot
(<code>COND_STATUS_CD &gt; 1</code>). Hence it appears Plot B straddles
an upland, wetland, and non-forested boundary!</p>
</div>
<div id="basic-estimation-procedures" class="section level2">
<h2>Basic Estimation Procedures</h2>
<p>Now that we have the data for our two example plots, let’s put them
to work estimating tree biomass and carbon. First, we will join the
plot, condition, and tree tables for each plot:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>tbl_a <span class="ot">&lt;-</span> plot_a <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>  <span class="co"># Rename the CN column in plot, PLT_CN for simple joining</span></span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PLT_CN =</span> CN) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>  <span class="co"># Join tables</span></span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>  <span class="fu">left_join</span>(cond_a, <span class="at">by =</span> <span class="st">&#39;PLT_CN&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>  <span class="fu">left_join</span>(tree_a, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;PLT_CN&#39;</span>, <span class="st">&#39;CONDID&#39;</span>))</span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a>tbl_b <span class="ot">&lt;-</span> plot_b <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a>  <span class="co"># Rename the CN column in plot, PLT_CN for simple joining</span></span>
<span id="cb11-11"><a href="#cb11-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PLT_CN =</span> CN) <span class="sc">%&gt;%</span></span>
<span id="cb11-12"><a href="#cb11-12" tabindex="-1"></a>  <span class="co"># Join tables</span></span>
<span id="cb11-13"><a href="#cb11-13" tabindex="-1"></a>  <span class="fu">left_join</span>(cond_b, <span class="at">by =</span> <span class="st">&#39;PLT_CN&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-14"><a href="#cb11-14" tabindex="-1"></a>  <span class="fu">left_join</span>(tree_b, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;PLT_CN&#39;</span>, <span class="st">&#39;CONDID&#39;</span>))</span></code></pre></div>
<p>Joining tables is important when we want to produce estimates grouped
by fields in the plot or condition table. Otherwise, it would be
possible to only use the TREE table to compute estimates below.</p>
<p>To produce an estimate of the aboveground biomass and carbon per acre
represented by all trees on the plot, we can simply sum the aboveground
biomass (<code>DRYBIO_AG</code>) and carbon (<code>CARBON_AG</code>)
contained in each tree multiplied by the trees per acre each tree
represents (<code>TPA_UNADJ</code>). Notice that we also divide by 200
here to convert estimates from lbs/acre to short tons/acre, matching the
units of <code>rFIA</code> output.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>all_a <span class="ot">&lt;-</span> tbl_a <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>  <span class="fu">group_by</span>(PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_ACRE =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>all_b <span class="ot">&lt;-</span> tbl_b <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a>  <span class="fu">group_by</span>(PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_ACRE =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<p>If you have been following along in your own R session, let’s check
our estimates against <code>rFIA</code>. We’ve got a match!</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># Producing biomass estimates on all plots in RI, for all trees on forestland</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>rFIA_all <span class="ot">&lt;-</span> <span class="fu">biomass</span>(fiaRI, <span class="at">byPlot =</span> <span class="cn">TRUE</span>, <span class="at">treeType =</span> <span class="st">&#39;all&#39;</span>)</span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a><span class="fu">filter</span>(rFIA_all, PLT_CN <span class="sc">==</span> a)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##    YEAR pltID       PLT_CN BIO_ACRE CARB_ACRE PROP_FOREST
##   &lt;int&gt; &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1  2014 1_44_7_288 1.68e14     93.0      44.6           1</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>all_a</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##    PLT_CN BIO_AG_ACRE CARB_AG_ACRE
##     &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
## 1 1.68e14        93.0         44.6</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a><span class="fu">filter</span>(rFIA_all, PLT_CN <span class="sc">==</span> b)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##    YEAR pltID      PLT_CN BIO_ACRE CARB_ACRE PROP_FOREST
##   &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1  2014 1_44_3_52 1.68e14     118.      56.3       0.970</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>all_b</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##    PLT_CN BIO_AG_ACRE CARB_AG_ACRE
##     &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
## 1 1.68e14        118.         56.3</code></pre>
</div>
<div id="unique-domains-of-interest" class="section level2">
<h2>Unique domains of interest</h2>
<p>But what if we want to produce estimates for a specific kind of tree?
Say Northern Red Oak (<code>SPCD = 833</code>) which is greater than 12
inches DBH (<code>DIA &gt; 12</code>). We accomplish this using what <a href="https://www.srs.fs.usda.gov/pubs/gtr/gtr_srs080/gtr_srs080.pdf">Bechtold
and Patterson (2005)</a> call a ‘domain indicator’. This is essentially
just a vector which indicates whether a tree (or plot, condition, etc.)
is within our domain of interest (red oak &gt; 12).</p>
<p>To construct the domain indicator, we just need a vector which is the
same length as our joined table, and takes a value of 1 if the stem is
in the domain and 0 otherwise:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>tbl_a <span class="ot">&lt;-</span> tbl_a <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tDI =</span> <span class="fu">if_else</span>(SPCD <span class="sc">==</span> <span class="dv">833</span> <span class="sc">&amp;</span> DIA <span class="sc">&gt;</span> <span class="dv">12</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb21-4"><a href="#cb21-4" tabindex="-1"></a><span class="co"># The domain indicator</span></span>
<span id="cb21-5"><a href="#cb21-5" tabindex="-1"></a>tbl_a<span class="sc">$</span>tDI</span></code></pre></div>
<pre><code>##  [1] 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="co"># How many trees meet the criteria?</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a><span class="fu">sum</span>(tbl_a<span class="sc">$</span>tDI, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>tbl_b <span class="ot">&lt;-</span> tbl_b <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tDI =</span> <span class="fu">if_else</span>(SPCD <span class="sc">==</span> <span class="dv">833</span> <span class="sc">&amp;</span> DIA <span class="sc">&gt;</span> <span class="dv">12</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a><span class="co"># The domain indicator</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a>tbl_b<span class="sc">$</span>tDI</span></code></pre></div>
<pre><code>##  [1]  0  1  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1
## [26]  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
## [51]  0  0  0  0 NA</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="co"># How many trees meet the criteria?</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a><span class="fu">sum</span>(tbl_b<span class="sc">$</span>tDI, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Now we can use our new domain indicator (vector of 0s and 1s,
<code>tDI</code>) to produce estimates for any type of tree we specify!
By adding <code>tDI</code> to the basic estimation procedures below, we
force any tree which is not in our domain of interest to take a value of
zero. Therefore, only trees which are within the domain of interest
contribute to the plot-level estimate.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>ro12_a <span class="ot">&lt;-</span> tbl_a <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a>  <span class="fu">group_by</span>(PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_ACRE =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tDI <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb29-5"><a href="#cb29-5" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tDI<span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb29-6"><a href="#cb29-6" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb29-7"><a href="#cb29-7" tabindex="-1"></a>ro12_b <span class="ot">&lt;-</span> tbl_b <span class="sc">%&gt;%</span></span>
<span id="cb29-8"><a href="#cb29-8" tabindex="-1"></a>  <span class="fu">group_by</span>(PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="#cb29-9" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_ACRE =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tDI <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb29-10"><a href="#cb29-10" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tDI <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb29-11"><a href="#cb29-11" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" tabindex="-1"></a><span class="co"># Now let&#39;s check our estimates against rFIA --&gt; We&#39;ve got a match!</span></span>
<span id="cb29-13"><a href="#cb29-13" tabindex="-1"></a>rFIA_ro12 <span class="ot">&lt;-</span> <span class="fu">biomass</span>(fiaRI, <span class="at">byPlot =</span> <span class="cn">TRUE</span>, <span class="at">treeType =</span> <span class="st">&#39;all&#39;</span>, <span class="at">treeDomain =</span> SPCD <span class="sc">==</span> <span class="dv">833</span> <span class="sc">&amp;</span> DIA <span class="sc">&gt;</span> <span class="dv">12</span>)</span>
<span id="cb29-14"><a href="#cb29-14" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb29-15"><a href="#cb29-15" tabindex="-1"></a><span class="fu">filter</span>(rFIA_ro12, PLT_CN <span class="sc">==</span> a)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##    YEAR pltID       PLT_CN BIO_ACRE CARB_ACRE PROP_FOREST
##   &lt;int&gt; &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1  2014 1_44_7_288 1.68e14     22.3      10.7           1</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a>ro12_a</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##    PLT_CN BIO_AG_ACRE CARB_AG_ACRE
##     &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
## 1 1.68e14        22.3         10.7</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb33-2"><a href="#cb33-2" tabindex="-1"></a><span class="fu">filter</span>(rFIA_ro12, PLT_CN <span class="sc">==</span> b)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##    YEAR pltID      PLT_CN BIO_ACRE CARB_ACRE PROP_FOREST
##   &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1  2014 1_44_3_52 1.68e14     45.3      21.7       0.970</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>ro12_b</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##    PLT_CN BIO_AG_ACRE CARB_AG_ACRE
##     &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
## 1 1.68e14        45.3         21.7</code></pre>
</div>
<div id="grouped-estimation-procedures" class="section level2">
<h2>Grouped estimation procedures</h2>
<p>What if we want to produce estimates grouped by some attribute
contained in the FIA Database, like forest type? We can accomplish by
simply adding the attribute you want to group by to the
<code>group_by</code> call in the estimation procedures above. This will
then sum the biomass and carbon per acre of stems occuring on each
forest type seperately.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>for_a <span class="ot">&lt;-</span> tbl_a <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a>  <span class="co"># Adding FORTYPCD here</span></span>
<span id="cb37-4"><a href="#cb37-4" tabindex="-1"></a>  <span class="fu">group_by</span>(PLT_CN, FORTYPCD) <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="#cb37-5" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_ACRE =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-6"><a href="#cb37-6" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ<span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-7"><a href="#cb37-7" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb37-8"><a href="#cb37-8" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb37-9"><a href="#cb37-9" tabindex="-1"></a>for_b <span class="ot">&lt;-</span> tbl_b <span class="sc">%&gt;%</span></span>
<span id="cb37-10"><a href="#cb37-10" tabindex="-1"></a>  <span class="co"># Adding FORTYPCD here</span></span>
<span id="cb37-11"><a href="#cb37-11" tabindex="-1"></a>  <span class="fu">group_by</span>(PLT_CN, FORTYPCD) <span class="sc">%&gt;%</span></span>
<span id="cb37-12"><a href="#cb37-12" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_ACRE =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ<span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-13"><a href="#cb37-13" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb37-14"><a href="#cb37-14" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb37-15"><a href="#cb37-15" tabindex="-1"></a></span>
<span id="cb37-16"><a href="#cb37-16" tabindex="-1"></a><span class="co"># Now let&#39;s check our estimates against rFIA --&gt; We&#39;ve got a match!</span></span>
<span id="cb37-17"><a href="#cb37-17" tabindex="-1"></a>rFIA_for <span class="ot">&lt;-</span> <span class="fu">biomass</span>(fiaRI, <span class="at">byPlot =</span> <span class="cn">TRUE</span>, <span class="at">treeType =</span> <span class="st">&#39;all&#39;</span>, <span class="at">grpBy =</span> FORTYPCD)</span>
<span id="cb37-18"><a href="#cb37-18" tabindex="-1"></a><span class="co"># Plot A</span></span>
<span id="cb37-19"><a href="#cb37-19" tabindex="-1"></a><span class="fu">filter</span>(rFIA_for, PLT_CN <span class="sc">==</span> a)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##    YEAR pltID      FORTYPCD  PLT_CN BIO_ACRE CARB_ACRE PROP_FOREST
##   &lt;int&gt; &lt;chr&gt;         &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1  2014 1_44_7_288      503 1.68e14     93.0      44.6           1</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>for_a <span class="co"># One forest type here, so only one row in the output</span></span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##    PLT_CN FORTYPCD BIO_AG_ACRE CARB_AG_ACRE
##     &lt;dbl&gt;    &lt;int&gt;       &lt;dbl&gt;        &lt;dbl&gt;
## 1 1.68e14      503        93.0         44.6</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" tabindex="-1"></a><span class="co"># Plot B</span></span>
<span id="cb41-2"><a href="#cb41-2" tabindex="-1"></a><span class="fu">filter</span>(rFIA_for, PLT_CN <span class="sc">==</span> b)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##    YEAR pltID     FORTYPCD  PLT_CN BIO_ACRE CARB_ACRE PROP_FOREST
##   &lt;int&gt; &lt;chr&gt;        &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1  2014 1_44_3_52      505 1.68e14    102.      48.4        0.75 
## 2  2014 1_44_3_52      708 1.68e14     16.2      7.86       0.220</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" tabindex="-1"></a>for_b <span class="co"># Two forest types here, so two rows in output, plus the non-forested row</span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##    PLT_CN FORTYPCD BIO_AG_ACRE CARB_AG_ACRE
##     &lt;dbl&gt;    &lt;int&gt;       &lt;dbl&gt;        &lt;dbl&gt;
## 1 1.68e14      505       102.         48.4 
## 2 1.68e14      708        16.2         7.86
## 3 1.68e14       NA         0           0</code></pre>
</div>
</div>
<div id="estimation-at-the-population-level" class="section level1">
<h1>Estimation at the population-level</h1>
<p>In the code below, we highlight the basic estimation procedures used
to compute population estimates of forest attributes from Forest
Inventory and Analysis (FIA) data. We will demonstrate these procedures
with the <code>fiaRI</code> dataset (included in the <code>rFIA</code>
package) so that you can follow along.</p>
<p>Our goal here is to estimate total tree biomass, total tree carbon
(aboveground) and total forested area in the state of Rhode Island for
the year 2018. From these totals, we will compute ratios of average tree
biomass/ forested acre and average tree carbon/ forested acre. We will
do this with and without sampling errors (without being much simpler),
and show you how we handle grouped estimates in both cases. All
estimates will be computed for live trees.</p>
<p>The source code for <code>rFIA</code> will vary slightly from that
presented below as we designed <code>rFIA</code> to be as flexible and
computationally efficient as possible. Despite the differences in syntax
and structure, the estimation procedures presented below are identical
to those in <code>rFIA</code>. You can find and download the full source
code for <code>rFIA</code> from our <a href="https://github.com/doserjef/rFIA">GitHub repository</a>.</p>
<div id="data-preparation" class="section level2">
<h2>Data Preparation</h2>
<p>First, let’s load some packages and the <code>fiaRI</code>
dataset:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a><span class="co"># Load some packages</span></span>
<span id="cb45-2"><a href="#cb45-2" tabindex="-1"></a><span class="fu">library</span>(rFIA)</span>
<span id="cb45-3"><a href="#cb45-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb45-4"><a href="#cb45-4" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" tabindex="-1"></a><span class="co"># Load the fiaRI dataset (included in rFIA)</span></span>
<span id="cb45-6"><a href="#cb45-6" tabindex="-1"></a><span class="fu">data</span>(fiaRI)</span>
<span id="cb45-7"><a href="#cb45-7" tabindex="-1"></a>db <span class="ot">&lt;-</span> fiaRI</span></code></pre></div>
<p>To compute population estimates of current area and current
biomass/carbon from the FIADB, we need to identify and subset the
necessary portions. To do this, we will use what FIA calls an EVALID,
hence the name ‘EVALIDator’.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a>ids <span class="ot">&lt;-</span> db<span class="sc">$</span>POP_EVAL <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">&#39;CN&#39;</span>, <span class="st">&#39;END_INVYR&#39;</span>, <span class="st">&#39;EVALID&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" tabindex="-1"></a>  <span class="fu">inner_join</span>(<span class="fu">select</span>(db<span class="sc">$</span>POP_EVAL_TYP, <span class="fu">c</span>(<span class="st">&#39;EVAL_CN&#39;</span>, <span class="st">&#39;EVAL_TYP&#39;</span>)), <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;CN&#39;</span> <span class="ot">=</span> <span class="st">&#39;EVAL_CN&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" tabindex="-1"></a>  <span class="co"># Now we filter out everything except current area (EXPCURR) and</span></span>
<span id="cb46-5"><a href="#cb46-5" tabindex="-1"></a>  <span class="co"># current volume ids (EXPVOL), and only grab those from 2018</span></span>
<span id="cb46-6"><a href="#cb46-6" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;EXPCURR&#39;</span>, <span class="st">&#39;EXPVOL&#39;</span>), END_INVYR <span class="sc">==</span> <span class="dv">2018</span>)</span>
<span id="cb46-7"><a href="#cb46-7" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" tabindex="-1"></a><span class="co"># Now that we have those EVALIDs, let&#39;s use clipFIA to subset</span></span>
<span id="cb46-10"><a href="#cb46-10" tabindex="-1"></a>db <span class="ot">&lt;-</span> <span class="fu">clipFIA</span>(db, <span class="at">mostRecent =</span> <span class="cn">FALSE</span>, <span class="at">evalid =</span> ids<span class="sc">$</span>EVALID)</span></code></pre></div>
<p>Since we need some information stored in each of these tables to
compute estimates, we will join them into one big dataframe (let’s call
that <code>data</code>) that we can operate on.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="co"># Select only the columns we need from each table, to keep things slim</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a>PLOT <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>PLOT, CN, MACRO_BREAKPOINT_DIA)</span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>COND <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>COND, PLT_CN, CONDID, CONDPROP_UNADJ, PROP_BASIS, </span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a>               COND_STATUS_CD, OWNGRPCD)</span>
<span id="cb47-5"><a href="#cb47-5" tabindex="-1"></a>TREE <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>TREE, PLT_CN, CONDID, SUBP, TREE, STATUSCD, </span>
<span id="cb47-6"><a href="#cb47-6" tabindex="-1"></a>               DRYBIO_AG, CARBON_AG, TPA_UNADJ, DIA, SPCD)</span>
<span id="cb47-7"><a href="#cb47-7" tabindex="-1"></a>POP_ESTN_UNIT <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>POP_ESTN_UNIT, CN, EVAL_CN, AREA_USED, </span>
<span id="cb47-8"><a href="#cb47-8" tabindex="-1"></a>                        P1PNTCNT_EU)</span>
<span id="cb47-9"><a href="#cb47-9" tabindex="-1"></a>POP_EVAL <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>POP_EVAL, EVALID, EVAL_GRP_CN, ESTN_METHOD, CN, </span>
<span id="cb47-10"><a href="#cb47-10" tabindex="-1"></a>                   END_INVYR, REPORT_YEAR_NM)</span>
<span id="cb47-11"><a href="#cb47-11" tabindex="-1"></a>POP_EVAL_TYP <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>POP_EVAL_TYP, EVAL_TYP, EVAL_CN)</span>
<span id="cb47-12"><a href="#cb47-12" tabindex="-1"></a>POP_PLOT_STRATUM_ASSGN <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>POP_PLOT_STRATUM_ASSGN, STRATUM_CN, </span>
<span id="cb47-13"><a href="#cb47-13" tabindex="-1"></a>                                 PLT_CN)</span>
<span id="cb47-14"><a href="#cb47-14" tabindex="-1"></a>POP_STRATUM <span class="ot">&lt;-</span> <span class="fu">select</span>(db<span class="sc">$</span>POP_STRATUM, ESTN_UNIT_CN, EXPNS, P2POINTCNT,</span>
<span id="cb47-15"><a href="#cb47-15" tabindex="-1"></a>                      ADJ_FACTOR_MICR, ADJ_FACTOR_SUBP, ADJ_FACTOR_MACR, </span>
<span id="cb47-16"><a href="#cb47-16" tabindex="-1"></a>                      CN, P1POINTCNT)</span>
<span id="cb47-17"><a href="#cb47-17" tabindex="-1"></a><span class="co"># Join the tables</span></span>
<span id="cb47-18"><a href="#cb47-18" tabindex="-1"></a>data <span class="ot">&lt;-</span> PLOT <span class="sc">%&gt;%</span></span>
<span id="cb47-19"><a href="#cb47-19" tabindex="-1"></a>  <span class="co"># Add a PLT_CN column for easy joining</span></span>
<span id="cb47-20"><a href="#cb47-20" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PLT_CN =</span> CN) <span class="sc">%&gt;%</span></span>
<span id="cb47-21"><a href="#cb47-21" tabindex="-1"></a>  <span class="co"># Join COND &amp; TREE</span></span>
<span id="cb47-22"><a href="#cb47-22" tabindex="-1"></a>  <span class="fu">left_join</span>(COND, <span class="at">by =</span> <span class="st">&#39;PLT_CN&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-23"><a href="#cb47-23" tabindex="-1"></a>  <span class="fu">left_join</span>(TREE, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;PLT_CN&#39;</span>, <span class="st">&#39;CONDID&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-24"><a href="#cb47-24" tabindex="-1"></a>  <span class="co"># Population tables</span></span>
<span id="cb47-25"><a href="#cb47-25" tabindex="-1"></a>  <span class="fu">left_join</span>(POP_PLOT_STRATUM_ASSGN, <span class="at">by =</span> <span class="st">&#39;PLT_CN&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-26"><a href="#cb47-26" tabindex="-1"></a>  <span class="fu">left_join</span>(POP_STRATUM, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;STRATUM_CN&#39;</span> <span class="ot">=</span> <span class="st">&#39;CN&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-27"><a href="#cb47-27" tabindex="-1"></a>  <span class="fu">left_join</span>(POP_ESTN_UNIT, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;ESTN_UNIT_CN&#39;</span> <span class="ot">=</span> <span class="st">&#39;CN&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-28"><a href="#cb47-28" tabindex="-1"></a>  <span class="fu">left_join</span>(POP_EVAL, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;EVAL_CN&#39;</span> <span class="ot">=</span> <span class="st">&#39;CN&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-29"><a href="#cb47-29" tabindex="-1"></a>  <span class="fu">left_join</span>(POP_EVAL_TYP, <span class="at">by =</span> <span class="st">&#39;EVAL_CN&#39;</span>, <span class="at">relationship =</span> <span class="st">&#39;many-to-many&#39;</span>)</span></code></pre></div>
<p>Now let’s make a column that will adjust for non-response in our
sample (See <a href="https://www.srs.fs.usda.gov/pubs/gtr/gtr_srs080/gtr_srs080.pdf">Bechtold
and Patterson (2005)</a>, 3.4.3 ‘Nonsampled Plots and Plot
Replacement’). Since we know there are no macroplots in RI, we don’t
really need to worry about that here, but we will show you anyways.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a><span class="co"># Make some adjustment factors</span></span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-4"><a href="#cb48-4" tabindex="-1"></a>    <span class="co"># AREA</span></span>
<span id="cb48-5"><a href="#cb48-5" tabindex="-1"></a>    <span class="at">aAdj =</span> <span class="fu">case_when</span>(</span>
<span id="cb48-6"><a href="#cb48-6" tabindex="-1"></a>           <span class="co"># When NA, stay NA</span></span>
<span id="cb48-7"><a href="#cb48-7" tabindex="-1"></a>           <span class="fu">is.na</span>(PROP_BASIS) <span class="sc">~</span> <span class="cn">NA_real_</span>,</span>
<span id="cb48-8"><a href="#cb48-8" tabindex="-1"></a>           <span class="co"># If the proportion was measured for a macroplot,</span></span>
<span id="cb48-9"><a href="#cb48-9" tabindex="-1"></a>           <span class="co"># use the macroplot value</span></span>
<span id="cb48-10"><a href="#cb48-10" tabindex="-1"></a>           PROP_BASIS <span class="sc">==</span> <span class="st">&#39;MACR&#39;</span> <span class="sc">~</span> <span class="fu">as.numeric</span>(ADJ_FACTOR_MACR),</span>
<span id="cb48-11"><a href="#cb48-11" tabindex="-1"></a>           <span class="co"># Otherwise, use the subpplot value</span></span>
<span id="cb48-12"><a href="#cb48-12" tabindex="-1"></a>           PROP_BASIS <span class="sc">==</span> <span class="st">&#39;SUBP&#39;</span> <span class="sc">~</span> ADJ_FACTOR_SUBP),</span>
<span id="cb48-13"><a href="#cb48-13" tabindex="-1"></a>    <span class="co"># TREE</span></span>
<span id="cb48-14"><a href="#cb48-14" tabindex="-1"></a>    <span class="at">tAdj =</span> <span class="fu">case_when</span>(</span>
<span id="cb48-15"><a href="#cb48-15" tabindex="-1"></a>           <span class="co"># When DIA is na, adjustment is NA</span></span>
<span id="cb48-16"><a href="#cb48-16" tabindex="-1"></a>           <span class="fu">is.na</span>(DIA) <span class="sc">~</span> ADJ_FACTOR_SUBP,</span>
<span id="cb48-17"><a href="#cb48-17" tabindex="-1"></a>           <span class="co"># When DIA is less than 5&quot;, use microplot value</span></span>
<span id="cb48-18"><a href="#cb48-18" tabindex="-1"></a>           DIA <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> ADJ_FACTOR_MICR,</span>
<span id="cb48-19"><a href="#cb48-19" tabindex="-1"></a>           <span class="co"># When DIA is greater than 5&quot;, use subplot value</span></span>
<span id="cb48-20"><a href="#cb48-20" tabindex="-1"></a>           DIA <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">~</span> ADJ_FACTOR_SUBP</span>
<span id="cb48-21"><a href="#cb48-21" tabindex="-1"></a>         )</span>
<span id="cb48-22"><a href="#cb48-22" tabindex="-1"></a>  )</span></code></pre></div>
<p>Next, we need to construct what <a href="https://www.srs.fs.usda.gov/pubs/gtr/gtr_srs080/gtr_srs080.pdf">Bechtold
and Patterson (2005)</a> called a ‘domain indicator function’. (see Eq.
4.1, pg. 47 of the publication). This is essentially just a vector which
indicates whether a tree (or plot, condition, etc.) is within our domain
of interest (live trees on forest land).</p>
<p>To construct the domain indicator, we just need a vector which is the
same length as our joined table (<code>data</code>), and takes a value
of 1 if the stem (or condition) is in the domain and 0 otherwise. We
build separate domain indicators for estimating tree totals and area
totals, because we can specify different domains of interest for both.
For example, if we used our tree domain (live trees on forest land) to
estimate area, then we would not actually be estimating the full
forested area in RI. Instead we would estimate the forested area ONLY
where live trees are currently present.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a><span class="co"># Build a domain indicator for land type and live trees</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a><span class="co"># Land type (all forested area)</span></span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a>data<span class="sc">$</span>aDI <span class="ot">&lt;-</span> <span class="fu">if_else</span>(data<span class="sc">$</span>COND_STATUS_CD <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb49-4"><a href="#cb49-4" tabindex="-1"></a><span class="co"># Live trees only (on forested area)</span></span>
<span id="cb49-5"><a href="#cb49-5" tabindex="-1"></a>data<span class="sc">$</span>tDI <span class="ot">&lt;-</span> <span class="fu">if_else</span>(data<span class="sc">$</span>STATUSCD <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">*</span> data<span class="sc">$</span>aDI</span>
<span id="cb49-6"><a href="#cb49-6" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" tabindex="-1"></a><span class="co"># Now, let&#39;s just rename the END_INVYR column to &#39;YEAR&#39;</span></span>
<span id="cb49-8"><a href="#cb49-8" tabindex="-1"></a><span class="co"># for a pretty output like rFIA</span></span>
<span id="cb49-9"><a href="#cb49-9" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb49-10"><a href="#cb49-10" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">YEAR =</span> END_INVYR) <span class="sc">%&gt;%</span></span>
<span id="cb49-11"><a href="#cb49-11" tabindex="-1"></a>  <span class="co"># remove any NAs</span></span>
<span id="cb49-12"><a href="#cb49-12" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(YEAR))</span></code></pre></div>
</div>
<div id="without-sampling-errors" class="section level2">
<h2>Without Sampling Errors</h2>
<p>Now we are ready to start computing estimates. If we don’t care
aboute sampling errors, we can use the <code>EXPNS</code> column in the
<code>POP_STRATUM</code> table to make our lives easier.
<code>EXPNS</code> is an expansion factor which descibes the area, in
acres, that a stratum represents divided by the number of sampled plots
in that stratum (see <a href="https://www.srs.fs.usda.gov/pubs/gtr/gtr_srs080/gtr_srs080.pdf">Bechtold
and Patterson (2005)</a> section 4.2 for more information on FIA
stratification procedures). When summed across all plots in the
population of interest, <code>EXPNS</code> allows us to easily obtain
estimates of population totals, without worrying about fancy
stratifaction procedures and variance estimators.</p>
<div id="no-grouping-variables" class="section level3">
<h3>No grouping variables</h3>
<p>First we compute totals for biomass, carbon, and forested area:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a><span class="co"># Estimate Tree totals</span></span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a>tre_bio <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPVOL&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-4"><a href="#cb50-4" tabindex="-1"></a>  <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb50-5"><a href="#cb50-5" tabindex="-1"></a>  <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, SUBP, TREE, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-6"><a href="#cb50-6" tabindex="-1"></a>  <span class="co"># Plot-level estimates first (multiplying by EXPNS here)</span></span>
<span id="cb50-7"><a href="#cb50-7" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTN_UNIT_CN, ESTN_METHOD, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb50-8"><a href="#cb50-8" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">bioPlot =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI <span class="sc">*</span> EXPNS  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb50-9"><a href="#cb50-9" tabindex="-1"></a>            <span class="at">carbPlot =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI <span class="sc">*</span> EXPNS  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb50-10"><a href="#cb50-10" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-11"><a href="#cb50-11" tabindex="-1"></a>  <span class="co"># Now we simply sum the values of each plot (expanded w/ EXPNS)</span></span>
<span id="cb50-12"><a href="#cb50-12" tabindex="-1"></a>  <span class="co"># to obtain population totals</span></span>
<span id="cb50-13"><a href="#cb50-13" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb50-14"><a href="#cb50-14" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_TOTAL =</span> <span class="fu">sum</span>(bioPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb50-15"><a href="#cb50-15" tabindex="-1"></a>            <span class="at">CARB_AG_TOTAL =</span> <span class="fu">sum</span>(carbPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb50-16"><a href="#cb50-16" tabindex="-1"></a></span>
<span id="cb50-17"><a href="#cb50-17" tabindex="-1"></a><span class="co"># Estimate Area totals</span></span>
<span id="cb50-18"><a href="#cb50-18" tabindex="-1"></a>area_bio <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb50-19"><a href="#cb50-19" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPCURR&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-20"><a href="#cb50-20" tabindex="-1"></a>  <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb50-21"><a href="#cb50-21" tabindex="-1"></a>  <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-22"><a href="#cb50-22" tabindex="-1"></a>  <span class="co"># Plot-level estimates first (multiplying by EXPNS here)</span></span>
<span id="cb50-23"><a href="#cb50-23" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTN_UNIT_CN, ESTN_METHOD, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb50-24"><a href="#cb50-24" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">forArea =</span> <span class="fu">sum</span>(CONDPROP_UNADJ <span class="sc">*</span> aAdj <span class="sc">*</span> aDI <span class="sc">*</span> EXPNS, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb50-25"><a href="#cb50-25" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-26"><a href="#cb50-26" tabindex="-1"></a>  <span class="co"># Now we simply sum the values of each plot (expanded w/ EXPNS)</span></span>
<span id="cb50-27"><a href="#cb50-27" tabindex="-1"></a>  <span class="co"># to obtain population totals</span></span>
<span id="cb50-28"><a href="#cb50-28" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb50-29"><a href="#cb50-29" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">AREA_TOTAL =</span> <span class="fu">sum</span>(forArea, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<p>Then we can join these tables up, and produce ratio estimates:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a>bio <span class="ot">&lt;-</span> <span class="fu">left_join</span>(tre_bio, area_bio) <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">BIO_AG_ACRE =</span> BIO_AG_TOTAL <span class="sc">/</span> AREA_TOTAL,</span>
<span id="cb51-3"><a href="#cb51-3" tabindex="-1"></a>         <span class="at">CARB_AG_ACRE =</span> CARB_AG_TOTAL <span class="sc">/</span> AREA_TOTAL) <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="#cb51-4" tabindex="-1"></a>  <span class="co"># Reordering the columns</span></span>
<span id="cb51-5"><a href="#cb51-5" tabindex="-1"></a>  <span class="fu">select</span>(YEAR, BIO_AG_ACRE, CARB_AG_ACRE, BIO_AG_TOTAL, CARB_AG_TOTAL, AREA_TOTAL)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(YEAR)`</code></pre>
<p>Comparing with <code>rFIA</code>, we get a match!</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="fu">biomass</span>(<span class="fu">clipFIA</span>(fiaRI), <span class="at">totals =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 14
##    YEAR BIO_ACRE CARB_ACRE BIO_TOTAL CARB_TOTAL AREA_TOTAL BIO_ACRE_SE
##   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
## 1  2018     75.7      36.6 27762772.  13427961.    366959.        3.87
## # ℹ 7 more variables: CARB_ACRE_SE &lt;dbl&gt;, BIO_TOTAL_SE &lt;dbl&gt;,
## #   CARB_TOTAL_SE &lt;dbl&gt;, AREA_TOTAL_SE &lt;dbl&gt;, nPlots_TREE &lt;int&gt;,
## #   nPlots_AREA &lt;int&gt;, N &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a>bio</span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##    YEAR BIO_AG_ACRE CARB_AG_ACRE BIO_AG_TOTAL CARB_AG_TOTAL AREA_TOTAL
##   &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;
## 1  2018        75.7         36.6    27762772.     13427961.    366959.</code></pre>
</div>
<div id="adding-grouping-variables" class="section level3">
<h3>Adding grouping variables</h3>
<p>To add grouping variables to the above procedures, we can simply add
the names of the variables we wish to group by to the
<code>group_by</code> call:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="co"># Grouping by Ownership group (OWNGRPCD)</span></span>
<span id="cb57-2"><a href="#cb57-2" tabindex="-1"></a><span class="co"># Estimate Tree totals</span></span>
<span id="cb57-3"><a href="#cb57-3" tabindex="-1"></a>tre_bioGrp <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb57-4"><a href="#cb57-4" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPVOL&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-5"><a href="#cb57-5" tabindex="-1"></a>  <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb57-6"><a href="#cb57-6" tabindex="-1"></a>  <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, SUBP, TREE, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-7"><a href="#cb57-7" tabindex="-1"></a>  <span class="co"># Plot-level estimates first (multiplying by EXPNS here)</span></span>
<span id="cb57-8"><a href="#cb57-8" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, OWNGRPCD, ESTN_UNIT_CN, ESTN_METHOD, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb57-9"><a href="#cb57-9" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">bioPlot =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI <span class="sc">*</span> EXPNS  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb57-10"><a href="#cb57-10" tabindex="-1"></a>            <span class="at">carbPlot =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI <span class="sc">*</span> EXPNS  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb57-11"><a href="#cb57-11" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-12"><a href="#cb57-12" tabindex="-1"></a>  <span class="co"># Now we simply sum the values of each plot (expanded w/ EXPNS)</span></span>
<span id="cb57-13"><a href="#cb57-13" tabindex="-1"></a>  <span class="co"># to obtain population totals</span></span>
<span id="cb57-14"><a href="#cb57-14" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, OWNGRPCD) <span class="sc">%&gt;%</span></span>
<span id="cb57-15"><a href="#cb57-15" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">BIO_AG_TOTAL =</span> <span class="fu">sum</span>(bioPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb57-16"><a href="#cb57-16" tabindex="-1"></a>            <span class="at">CARB_AG_TOTAL =</span> <span class="fu">sum</span>(carbPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb57-17"><a href="#cb57-17" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb57-18"><a href="#cb57-18" tabindex="-1"></a></span>
<span id="cb57-19"><a href="#cb57-19" tabindex="-1"></a><span class="co"># Estimate Area totals</span></span>
<span id="cb57-20"><a href="#cb57-20" tabindex="-1"></a>area_bioGrp <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb57-21"><a href="#cb57-21" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPCURR&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-22"><a href="#cb57-22" tabindex="-1"></a>  <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb57-23"><a href="#cb57-23" tabindex="-1"></a>  <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-24"><a href="#cb57-24" tabindex="-1"></a>  <span class="co"># Plot-level estimates first (multiplying by EXPNS here)</span></span>
<span id="cb57-25"><a href="#cb57-25" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, OWNGRPCD, ESTN_UNIT_CN, ESTN_METHOD, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb57-26"><a href="#cb57-26" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">forArea =</span> <span class="fu">sum</span>(CONDPROP_UNADJ <span class="sc">*</span> aAdj <span class="sc">*</span> aDI <span class="sc">*</span> EXPNS, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb57-27"><a href="#cb57-27" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-28"><a href="#cb57-28" tabindex="-1"></a>  <span class="co"># Now we simply sum the values of each plot (expanded w/ EXPNS)</span></span>
<span id="cb57-29"><a href="#cb57-29" tabindex="-1"></a>  <span class="co"># to obtain population totals</span></span>
<span id="cb57-30"><a href="#cb57-30" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, OWNGRPCD) <span class="sc">%&gt;%</span></span>
<span id="cb57-31"><a href="#cb57-31" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">AREA_TOTAL =</span> <span class="fu">sum</span>(forArea, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb57-32"><a href="#cb57-32" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb57-33"><a href="#cb57-33" tabindex="-1"></a></span>
<span id="cb57-34"><a href="#cb57-34" tabindex="-1"></a><span class="co"># Now we can simply join these two up, and produce ratio estimates</span></span>
<span id="cb57-35"><a href="#cb57-35" tabindex="-1"></a>bioGrp <span class="ot">&lt;-</span> <span class="fu">left_join</span>(tre_bioGrp, area_bioGrp) <span class="sc">%&gt;%</span></span>
<span id="cb57-36"><a href="#cb57-36" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">BIO_AG_ACRE =</span> BIO_AG_TOTAL <span class="sc">/</span> AREA_TOTAL,</span>
<span id="cb57-37"><a href="#cb57-37" tabindex="-1"></a>         <span class="at">CARB_AG_ACRE =</span> CARB_AG_TOTAL <span class="sc">/</span> AREA_TOTAL) <span class="sc">%&gt;%</span></span>
<span id="cb57-38"><a href="#cb57-38" tabindex="-1"></a>  <span class="co"># Reordering the columns</span></span>
<span id="cb57-39"><a href="#cb57-39" tabindex="-1"></a>  <span class="fu">select</span>(YEAR, OWNGRPCD, BIO_AG_ACRE, CARB_AG_ACRE, BIO_AG_TOTAL, CARB_AG_TOTAL, AREA_TOTAL)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(YEAR, OWNGRPCD)`</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" tabindex="-1"></a><span class="co"># Now let&#39;s compare with rFIA.... looks like a match!</span></span>
<span id="cb59-2"><a href="#cb59-2" tabindex="-1"></a><span class="fu">biomass</span>(<span class="fu">clipFIA</span>(fiaRI), <span class="at">totals =</span> <span class="cn">TRUE</span>, <span class="at">grpBy =</span> OWNGRPCD)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 15
##    YEAR OWNGRPCD BIO_ACRE CARB_ACRE BIO_TOTAL CARB_TOTAL AREA_TOTAL BIO_ACRE_SE
##   &lt;dbl&gt;    &lt;int&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
## 1  2018       30     77.2      37.5  8622383.   4186531.    111642.        8.53
## 2  2018       40     75.0      36.2 19140389.   9241429.    255317.        4.12
## # ℹ 7 more variables: CARB_ACRE_SE &lt;dbl&gt;, BIO_TOTAL_SE &lt;dbl&gt;,
## #   CARB_TOTAL_SE &lt;dbl&gt;, AREA_TOTAL_SE &lt;dbl&gt;, nPlots_TREE &lt;int&gt;,
## #   nPlots_AREA &lt;int&gt;, N &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a>bioGrp</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##    YEAR OWNGRPCD BIO_AG_ACRE CARB_AG_ACRE BIO_AG_TOTAL CARB_AG_TOTAL AREA_TOTAL
##   &lt;dbl&gt;    &lt;int&gt;       &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;
## 1  2018       30        77.2         37.5     8622383.      4186531.    111642.
## 2  2018       40        75.0         36.2    19140389.      9241429.    255317.
## 3  2018       NA       NaN          NaN             0             0          0</code></pre>
<p>If adapting this code for your own use, make sure that your grouping
variables are included in the <code>select</code> calls in <strong>Data
Prepration</strong>, otherwise the variable will not be found in
<code>data</code>.</p>
</div>
</div>
<div id="with-sampling-errors" class="section level2">
<h2>With Sampling Errors</h2>
<p>Computing estimates with associated sampling errors is a bit more
complex than what we saw above, as we can no longer rely on
<code>EXPNS</code> to do the heavy lifting for us. In short, we will add
a few additional steps when computing tree totals and area totals,
summarizing at the strata and estimation unit level along the way. When
adding grouping variables, we will need to modify our code further,
treating each group as a unique population and summarizing these
populations individually. We will follow the procedures outlined by <a href="https://www.srs.fs.usda.gov/pubs/gtr/gtr_srs080/gtr_srs080.pdf">Bechtold
and Patterson (2005)</a> (see section 4) for our computations.</p>
<p>Before we get started, Let’s check out what type of estimation
methods were used to determine values in the POP tables, as this will
influence which variance estimators we use.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" tabindex="-1"></a><span class="fu">unique</span>(db<span class="sc">$</span>POP_EVAL<span class="sc">$</span>ESTN_METHOD)</span></code></pre></div>
<pre><code>## [1] &quot;Post-Stratification&quot;</code></pre>
<p>Looks like just <code>post-stratification</code>, so we will use the
stratified random sampling estimation approach (known weights)</p>
<div id="no-grouping-variables-1" class="section level3">
<h3>No grouping variables</h3>
<p>First we estimate both tree and area attributes at the plot level,
and then join these estimates before proceeding to the strata level so
that we can compute the covariance between area and tree attributes</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a><span class="co"># Estimate Tree attributes -- plot level</span></span>
<span id="cb65-2"><a href="#cb65-2" tabindex="-1"></a>tre_pop <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPVOL&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" tabindex="-1"></a>  <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb65-5"><a href="#cb65-5" tabindex="-1"></a>  <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, SUBP, TREE, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-6"><a href="#cb65-6" tabindex="-1"></a>  <span class="co"># Plot-level estimates first (note we are NOT using EXPNS here)</span></span>
<span id="cb65-7"><a href="#cb65-7" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTN_UNIT_CN, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb65-8"><a href="#cb65-8" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">bioPlot =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb65-9"><a href="#cb65-9" tabindex="-1"></a>            <span class="at">carbPlot =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb65-10"><a href="#cb65-10" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb65-11"><a href="#cb65-11" tabindex="-1"></a></span>
<span id="cb65-12"><a href="#cb65-12" tabindex="-1"></a><span class="co"># Estimate Area attributes -- plot level</span></span>
<span id="cb65-13"><a href="#cb65-13" tabindex="-1"></a>area_pop <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb65-14"><a href="#cb65-14" tabindex="-1"></a>  <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPCURR&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-15"><a href="#cb65-15" tabindex="-1"></a>  <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb65-16"><a href="#cb65-16" tabindex="-1"></a>  <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-17"><a href="#cb65-17" tabindex="-1"></a>  <span class="co"># Plot-level estimates first (multiplying by EXPNS here)</span></span>
<span id="cb65-18"><a href="#cb65-18" tabindex="-1"></a>  <span class="co"># Extra grouping variables are only here so they are carried through</span></span>
<span id="cb65-19"><a href="#cb65-19" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, P1POINTCNT, P1PNTCNT_EU, P2POINTCNT, AREA_USED, ESTN_UNIT_CN, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb65-20"><a href="#cb65-20" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">forArea =</span> <span class="fu">sum</span>(CONDPROP_UNADJ <span class="sc">*</span> aAdj <span class="sc">*</span> aDI, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb65-21"><a href="#cb65-21" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb65-22"><a href="#cb65-22" tabindex="-1"></a></span>
<span id="cb65-23"><a href="#cb65-23" tabindex="-1"></a><span class="co"># Joining the two tables</span></span>
<span id="cb65-24"><a href="#cb65-24" tabindex="-1"></a>bio_pop_plot <span class="ot">&lt;-</span> <span class="fu">left_join</span>(tre_pop, area_pop)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(YEAR, ESTN_UNIT_CN, STRATUM_CN, PLT_CN)`</code></pre>
<p>Now that we have both area and tree attributes in the same table, we
can follow through with the remaining estimation procedures at the
strata and estimation unit levels:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a><span class="co"># Strata level</span></span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>bio_pop_strat <span class="ot">&lt;-</span> bio_pop_plot <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTN_UNIT_CN, STRATUM_CN) <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">aStrat =</span> <span class="fu">mean</span>(forArea, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Area mean</span></span>
<span id="cb67-5"><a href="#cb67-5" tabindex="-1"></a>            <span class="at">bioStrat =</span> <span class="fu">mean</span>(bioPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Biomass mean</span></span>
<span id="cb67-6"><a href="#cb67-6" tabindex="-1"></a>            <span class="at">carbStrat =</span> <span class="fu">mean</span>(carbPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Carbon mean</span></span>
<span id="cb67-7"><a href="#cb67-7" tabindex="-1"></a>            <span class="co"># We don&#39;t want a vector of these values, since they are repeated</span></span>
<span id="cb67-8"><a href="#cb67-8" tabindex="-1"></a>            <span class="at">P2POINTCNT =</span> <span class="fu">first</span>(P2POINTCNT),</span>
<span id="cb67-9"><a href="#cb67-9" tabindex="-1"></a>            <span class="at">AREA_USED =</span> <span class="fu">first</span>(AREA_USED),</span>
<span id="cb67-10"><a href="#cb67-10" tabindex="-1"></a>            <span class="co"># Strata weight, relative to estimation unit</span></span>
<span id="cb67-11"><a href="#cb67-11" tabindex="-1"></a>            <span class="at">w =</span> <span class="fu">first</span>(P1POINTCNT) <span class="sc">/</span> <span class="fu">first</span>(P1PNTCNT_EU),</span>
<span id="cb67-12"><a href="#cb67-12" tabindex="-1"></a>            <span class="co"># Strata level variances</span></span>
<span id="cb67-13"><a href="#cb67-13" tabindex="-1"></a>            <span class="at">aVar =</span> (<span class="fu">sum</span>(forArea<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> aStrat<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> </span>
<span id="cb67-14"><a href="#cb67-14" tabindex="-1"></a>                   (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb67-15"><a href="#cb67-15" tabindex="-1"></a>            <span class="at">bioVar =</span> (<span class="fu">sum</span>(bioPlot<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> bioStrat<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> </span>
<span id="cb67-16"><a href="#cb67-16" tabindex="-1"></a>                     (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb67-17"><a href="#cb67-17" tabindex="-1"></a>            <span class="at">carbVar =</span> (<span class="fu">sum</span>(carbPlot<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> carbStrat<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> </span>
<span id="cb67-18"><a href="#cb67-18" tabindex="-1"></a>                      (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb67-19"><a href="#cb67-19" tabindex="-1"></a>            <span class="co"># Strata level co-varainces</span></span>
<span id="cb67-20"><a href="#cb67-20" tabindex="-1"></a>            <span class="at">bioCV =</span> (<span class="fu">sum</span>(forArea<span class="sc">*</span>bioPlot) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> aStrat <span class="sc">*</span>bioStrat)) <span class="sc">/</span> </span>
<span id="cb67-21"><a href="#cb67-21" tabindex="-1"></a>                    (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb67-22"><a href="#cb67-22" tabindex="-1"></a>            <span class="at">carbCV =</span> (<span class="fu">sum</span>(forArea<span class="sc">*</span>carbPlot) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> aStrat <span class="sc">*</span>carbStrat)) <span class="sc">/</span> </span>
<span id="cb67-23"><a href="#cb67-23" tabindex="-1"></a>                     (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)), </span>
<span id="cb67-24"><a href="#cb67-24" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb67-25"><a href="#cb67-25" tabindex="-1"></a></span>
<span id="cb67-26"><a href="#cb67-26" tabindex="-1"></a><span class="co"># Moving on to the estimation unit</span></span>
<span id="cb67-27"><a href="#cb67-27" tabindex="-1"></a>bio_pop_eu <span class="ot">&lt;-</span> bio_pop_strat <span class="sc">%&gt;%</span></span>
<span id="cb67-28"><a href="#cb67-28" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, ESTN_UNIT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb67-29"><a href="#cb67-29" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">aEst =</span> <span class="fu">sum</span>(aStrat <span class="sc">*</span> w, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">first</span>(AREA_USED), <span class="co"># Mean Area</span></span>
<span id="cb67-30"><a href="#cb67-30" tabindex="-1"></a>            <span class="at">bioEst =</span> <span class="fu">sum</span>(bioStrat <span class="sc">*</span> w, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">first</span>(AREA_USED), <span class="co"># Mean biomass</span></span>
<span id="cb67-31"><a href="#cb67-31" tabindex="-1"></a>            <span class="at">carbEst =</span> <span class="fu">sum</span>(carbStrat <span class="sc">*</span> w, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">first</span>(AREA_USED), <span class="co"># Mean carbon</span></span>
<span id="cb67-32"><a href="#cb67-32" tabindex="-1"></a>            <span class="co"># Estimation unit variances</span></span>
<span id="cb67-33"><a href="#cb67-33" tabindex="-1"></a>            <span class="at">aVar =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb67-34"><a href="#cb67-34" tabindex="-1"></a>              (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>aVar) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>aVar)),</span>
<span id="cb67-35"><a href="#cb67-35" tabindex="-1"></a>            <span class="at">bioVar =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb67-36"><a href="#cb67-36" tabindex="-1"></a>              (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>bioVar) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>bioVar)),</span>
<span id="cb67-37"><a href="#cb67-37" tabindex="-1"></a>            <span class="at">carbVar =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb67-38"><a href="#cb67-38" tabindex="-1"></a>              (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>carbVar) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>carbVar)),</span>
<span id="cb67-39"><a href="#cb67-39" tabindex="-1"></a>            <span class="do">## Estimation unit covariances</span></span>
<span id="cb67-40"><a href="#cb67-40" tabindex="-1"></a>            <span class="at">bioCV =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb67-41"><a href="#cb67-41" tabindex="-1"></a>              (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>bioCV) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>bioCV)),</span>
<span id="cb67-42"><a href="#cb67-42" tabindex="-1"></a>            <span class="at">carbCV =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb67-43"><a href="#cb67-43" tabindex="-1"></a>              (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>carbCV) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>carbCV)), </span>
<span id="cb67-44"><a href="#cb67-44" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span></code></pre></div>
<p>Finally, we can sum attributes across estimation units to obtain
totals for our region:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a><span class="co"># sum across Estimation Units for totals</span></span>
<span id="cb68-2"><a href="#cb68-2" tabindex="-1"></a>bio_pop <span class="ot">&lt;-</span> bio_pop_eu <span class="sc">%&gt;%</span></span>
<span id="cb68-3"><a href="#cb68-3" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb68-4"><a href="#cb68-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">AREA_TOTAL =</span> <span class="fu">sum</span>(aEst, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb68-5"><a href="#cb68-5" tabindex="-1"></a>            <span class="at">BIO_AG_TOTAL =</span> <span class="fu">sum</span>(bioEst, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb68-6"><a href="#cb68-6" tabindex="-1"></a>            <span class="at">CARB_AG_TOTAL =</span> <span class="fu">sum</span>(carbEst, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb68-7"><a href="#cb68-7" tabindex="-1"></a>            <span class="co"># Ratios</span></span>
<span id="cb68-8"><a href="#cb68-8" tabindex="-1"></a>            <span class="at">BIO_AG_ACRE =</span> BIO_AG_TOTAL <span class="sc">/</span> AREA_TOTAL,</span>
<span id="cb68-9"><a href="#cb68-9" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE =</span> CARB_AG_TOTAL <span class="sc">/</span> AREA_TOTAL,</span>
<span id="cb68-10"><a href="#cb68-10" tabindex="-1"></a>            <span class="co"># Total samping errors</span></span>
<span id="cb68-11"><a href="#cb68-11" tabindex="-1"></a>            <span class="at">AREA_TOTAL_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(aVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> AREA_TOTAL <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb68-12"><a href="#cb68-12" tabindex="-1"></a>            <span class="at">BIO_AG_TOTAL_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(bioVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> BIO_AG_TOTAL <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb68-13"><a href="#cb68-13" tabindex="-1"></a>            <span class="at">CARB_AG_TOTAL_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(carbVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> CARB_AG_TOTAL <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb68-14"><a href="#cb68-14" tabindex="-1"></a>            <span class="co"># Ratio variances</span></span>
<span id="cb68-15"><a href="#cb68-15" tabindex="-1"></a>            <span class="at">bioAcreVar =</span> (<span class="dv">1</span> <span class="sc">/</span> AREA_TOTAL<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> (<span class="fu">sum</span>(bioVar) <span class="sc">+</span> </span>
<span id="cb68-16"><a href="#cb68-16" tabindex="-1"></a>                         (BIO_AG_ACRE<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span><span class="fu">sum</span>(aVar) <span class="sc">-</span> </span>
<span id="cb68-17"><a href="#cb68-17" tabindex="-1"></a>                         <span class="dv">2</span> <span class="sc">*</span> BIO_AG_ACRE <span class="sc">*</span> <span class="fu">sum</span>(bioCV)),</span>
<span id="cb68-18"><a href="#cb68-18" tabindex="-1"></a>            <span class="at">carbAcreVar =</span> (<span class="dv">1</span> <span class="sc">/</span> AREA_TOTAL<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> (<span class="fu">sum</span>(carbVar) <span class="sc">+</span> </span>
<span id="cb68-19"><a href="#cb68-19" tabindex="-1"></a>                          (CARB_AG_ACRE<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sum</span>(aVar) <span class="sc">-</span> </span>
<span id="cb68-20"><a href="#cb68-20" tabindex="-1"></a>                          <span class="dv">2</span> <span class="sc">*</span> CARB_AG_ACRE <span class="sc">*</span> <span class="fu">sum</span>(carbCV)),</span>
<span id="cb68-21"><a href="#cb68-21" tabindex="-1"></a>            <span class="at">BIO_AG_ACRE_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(bioAcreVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> </span>
<span id="cb68-22"><a href="#cb68-22" tabindex="-1"></a>                                  BIO_AG_ACRE <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb68-23"><a href="#cb68-23" tabindex="-1"></a>            <span class="at">CARB_AG_ACRE_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(carbAcreVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> </span>
<span id="cb68-24"><a href="#cb68-24" tabindex="-1"></a>                                   CARB_AG_ACRE <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb68-25"><a href="#cb68-25" tabindex="-1"></a>  <span class="co"># Re ordering, dropping variance</span></span>
<span id="cb68-26"><a href="#cb68-26" tabindex="-1"></a>  <span class="fu">select</span>(YEAR, BIO_AG_ACRE, CARB_AG_ACRE, BIO_AG_TOTAL, CARB_AG_TOTAL, </span>
<span id="cb68-27"><a href="#cb68-27" tabindex="-1"></a>         AREA_TOTAL, BIO_AG_ACRE_SE, CARB_AG_ACRE_SE, BIO_AG_TOTAL_SE, </span>
<span id="cb68-28"><a href="#cb68-28" tabindex="-1"></a>         CARB_AG_TOTAL_SE, AREA_TOTAL_SE)</span></code></pre></div>
<p>Comparing with <code>rFIA</code>, we get a match!</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a><span class="fu">glimpse</span>(<span class="fu">biomass</span>(<span class="fu">clipFIA</span>(fiaRI), <span class="at">totals =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## Rows: 1
## Columns: 14
## $ YEAR          &lt;dbl&gt; 2018
## $ BIO_ACRE      &lt;dbl&gt; 75.65639
## $ CARB_ACRE     &lt;dbl&gt; 36.59257
## $ BIO_TOTAL     &lt;dbl&gt; 27762772
## $ CARB_TOTAL    &lt;dbl&gt; 13427961
## $ AREA_TOTAL    &lt;dbl&gt; 366958.7
## $ BIO_ACRE_SE   &lt;dbl&gt; 3.874787
## $ CARB_ACRE_SE  &lt;dbl&gt; 3.901188
## $ BIO_TOTAL_SE  &lt;dbl&gt; 4.990582
## $ CARB_TOTAL_SE &lt;dbl&gt; 5.006351
## $ AREA_TOTAL_SE &lt;dbl&gt; 3.531998
## $ nPlots_TREE   &lt;int&gt; 126
## $ nPlots_AREA   &lt;int&gt; 127
## $ N             &lt;int&gt; 199</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" tabindex="-1"></a><span class="fu">glimpse</span>(bio_pop)</span></code></pre></div>
<pre><code>## Rows: 1
## Columns: 11
## $ YEAR             &lt;dbl&gt; 2018
## $ BIO_AG_ACRE      &lt;dbl&gt; 75.65639
## $ CARB_AG_ACRE     &lt;dbl&gt; 36.59257
## $ BIO_AG_TOTAL     &lt;dbl&gt; 27762772
## $ CARB_AG_TOTAL    &lt;dbl&gt; 13427961
## $ AREA_TOTAL       &lt;dbl&gt; 366958.7
## $ BIO_AG_ACRE_SE   &lt;dbl&gt; 3.874787
## $ CARB_AG_ACRE_SE  &lt;dbl&gt; 3.901188
## $ BIO_AG_TOTAL_SE  &lt;dbl&gt; 4.990582
## $ CARB_AG_TOTAL_SE &lt;dbl&gt; 5.006351
## $ AREA_TOTAL_SE    &lt;dbl&gt; 3.531998</code></pre>
</div>
<div id="adding-grouping-variables-1" class="section level3">
<h3>Adding grouping variables</h3>
<p>Unlike estimation without sampling errors, we can NOT just add
grouping variables to the above procedures in our <code>group_by</code>
call. Rather, we will need to account for absence points here (or
zero-length outputs) or our estimates will be artificially inflated if
groups are not mutually exclusive at the plot level. Example: The
presence of red oak on a plot does not negate the potential presence of
white ash on the same plot. Therefore, there should be a zero listed for
each species not found on the plot. We accomplish this by treating each
group as a separate population, computing each individually, and then
rejoining the groups at the end of the operation.</p>
<p>First let’s make a dataframe where each row defines a group that we
want to estimate:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a><span class="co"># All groups we want to estimate</span></span>
<span id="cb73-2"><a href="#cb73-2" tabindex="-1"></a>grps <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, SPCD) <span class="sc">%&gt;%</span></span>
<span id="cb73-4"><a href="#cb73-4" tabindex="-1"></a>  <span class="fu">summarize</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;YEAR&#39;. You can override using the
## `.groups` argument.</code></pre>
<p>Each row in <code>grps</code> now defines an individual population
that we would like to produce estimates for, thus our end product should
have the same number of rows. Thus, we can loop over each of the rows in
<code>grps</code> and use the estimation procedures above to estimate
attributes for each group.</p>
<p>Before we get started with the loop we need to find a way to define
the population of interest for each iteration (row). To do that, we will
modify our domain indicators from above to reflect whether or not an
observation falls within the population defined by
<code>grps[i,]</code>. Saving the original domain indicators as
variables so they are not overwritten in the loop:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a>tDI <span class="ot">&lt;-</span> data<span class="sc">$</span>tDI</span>
<span id="cb75-2"><a href="#cb75-2" tabindex="-1"></a>aDI <span class="ot">&lt;-</span> data<span class="sc">$</span>aDI</span></code></pre></div>
<p>Now we can start our loop:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a><span class="co"># Let&#39;s store each output in a list</span></span>
<span id="cb76-2"><a href="#cb76-2" tabindex="-1"></a>bio_pop <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb76-3"><a href="#cb76-3" tabindex="-1"></a><span class="co"># Looping</span></span>
<span id="cb76-4"><a href="#cb76-4" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(grps)){</span>
<span id="cb76-5"><a href="#cb76-5" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" tabindex="-1"></a>  <span class="co"># Tree domain indicator</span></span>
<span id="cb76-7"><a href="#cb76-7" tabindex="-1"></a>  data<span class="sc">$</span>tDI <span class="ot">&lt;-</span> tDI <span class="sc">*</span> <span class="fu">if_else</span>(data<span class="sc">$</span>SPCD <span class="sc">==</span> grps<span class="sc">$</span>SPCD[i], <span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">*</span> </span>
<span id="cb76-8"><a href="#cb76-8" tabindex="-1"></a>              <span class="fu">if_else</span>(data<span class="sc">$</span>YEAR <span class="sc">==</span> grps<span class="sc">$</span>YEAR[i], <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb76-9"><a href="#cb76-9" tabindex="-1"></a>  <span class="co"># No need to modify the area domain indicator for SPCD, because</span></span>
<span id="cb76-10"><a href="#cb76-10" tabindex="-1"></a>  <span class="co"># we want to estimate all forested area within the year</span></span>
<span id="cb76-11"><a href="#cb76-11" tabindex="-1"></a>  data<span class="sc">$</span>aDI <span class="ot">&lt;-</span> aDI <span class="sc">*</span> <span class="fu">if_else</span>(data<span class="sc">$</span>YEAR <span class="sc">==</span> grps<span class="sc">$</span>YEAR[i], <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb76-12"><a href="#cb76-12" tabindex="-1"></a></span>
<span id="cb76-13"><a href="#cb76-13" tabindex="-1"></a>  <span class="co"># SAME AS ABOVE, JUST IN A LOOP NOW --&gt; SIMILAR TO USING GROUP_BY</span></span>
<span id="cb76-14"><a href="#cb76-14" tabindex="-1"></a>  <span class="co"># Estimate Area attributes -- plot level</span></span>
<span id="cb76-15"><a href="#cb76-15" tabindex="-1"></a>  tre_pop <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb76-16"><a href="#cb76-16" tabindex="-1"></a>    <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPVOL&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-17"><a href="#cb76-17" tabindex="-1"></a>    <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb76-18"><a href="#cb76-18" tabindex="-1"></a>    <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, SUBP, TREE, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-19"><a href="#cb76-19" tabindex="-1"></a>    <span class="co"># Plot-level estimates first (note we are NOT using EXPNS here)</span></span>
<span id="cb76-20"><a href="#cb76-20" tabindex="-1"></a>    <span class="fu">group_by</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb76-21"><a href="#cb76-21" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">bioPlot =</span> <span class="fu">sum</span>(DRYBIO_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-22"><a href="#cb76-22" tabindex="-1"></a>              <span class="at">carbPlot =</span> <span class="fu">sum</span>(CARBON_AG <span class="sc">*</span> TPA_UNADJ <span class="sc">*</span> tAdj <span class="sc">*</span> tDI  <span class="sc">/</span> <span class="dv">2000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb76-23"><a href="#cb76-23" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb76-24"><a href="#cb76-24" tabindex="-1"></a></span>
<span id="cb76-25"><a href="#cb76-25" tabindex="-1"></a>  <span class="co"># Estimate Area attributes -- plot level</span></span>
<span id="cb76-26"><a href="#cb76-26" tabindex="-1"></a>  area_pop <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb76-27"><a href="#cb76-27" tabindex="-1"></a>    <span class="fu">filter</span>(EVAL_TYP <span class="sc">==</span> <span class="st">&#39;EXPCURR&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-28"><a href="#cb76-28" tabindex="-1"></a>    <span class="co"># Make sure we only have unique observations of plots, trees, etc.</span></span>
<span id="cb76-29"><a href="#cb76-29" tabindex="-1"></a>    <span class="fu">distinct</span>(ESTN_UNIT_CN, STRATUM_CN, PLT_CN, CONDID, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-30"><a href="#cb76-30" tabindex="-1"></a>    <span class="co"># Plot-level estimates first (multiplying by EXPNS here)</span></span>
<span id="cb76-31"><a href="#cb76-31" tabindex="-1"></a>    <span class="co"># Extra grouping variables are only here so they are carried through</span></span>
<span id="cb76-32"><a href="#cb76-32" tabindex="-1"></a>    <span class="fu">group_by</span>(P1POINTCNT, P1PNTCNT_EU, P2POINTCNT, AREA_USED, ESTN_UNIT_CN, STRATUM_CN, PLT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb76-33"><a href="#cb76-33" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">forArea =</span> <span class="fu">sum</span>(CONDPROP_UNADJ <span class="sc">*</span> aAdj <span class="sc">*</span> aDI, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb76-34"><a href="#cb76-34" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb76-35"><a href="#cb76-35" tabindex="-1"></a></span>
<span id="cb76-36"><a href="#cb76-36" tabindex="-1"></a>  <span class="co"># Joining the two tables</span></span>
<span id="cb76-37"><a href="#cb76-37" tabindex="-1"></a>  bio_pop_plot <span class="ot">&lt;-</span> <span class="fu">left_join</span>(tre_pop, area_pop)</span>
<span id="cb76-38"><a href="#cb76-38" tabindex="-1"></a></span>
<span id="cb76-39"><a href="#cb76-39" tabindex="-1"></a>  <span class="co"># Now we can follow through with the remaining estimation procedures</span></span>
<span id="cb76-40"><a href="#cb76-40" tabindex="-1"></a>  <span class="co"># Strata level</span></span>
<span id="cb76-41"><a href="#cb76-41" tabindex="-1"></a>  bio_pop_strat <span class="ot">&lt;-</span> bio_pop_plot <span class="sc">%&gt;%</span></span>
<span id="cb76-42"><a href="#cb76-42" tabindex="-1"></a>    <span class="fu">group_by</span>(ESTN_UNIT_CN, STRATUM_CN) <span class="sc">%&gt;%</span></span>
<span id="cb76-43"><a href="#cb76-43" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">aStrat =</span> <span class="fu">mean</span>(forArea, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Area mean</span></span>
<span id="cb76-44"><a href="#cb76-44" tabindex="-1"></a>              <span class="at">bioStrat =</span> <span class="fu">mean</span>(bioPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Biomass mean</span></span>
<span id="cb76-45"><a href="#cb76-45" tabindex="-1"></a>              <span class="at">carbStrat =</span> <span class="fu">mean</span>(carbPlot, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Carbon mean</span></span>
<span id="cb76-46"><a href="#cb76-46" tabindex="-1"></a>              <span class="co"># We don&#39;t want a vector of these values, since they are repeated</span></span>
<span id="cb76-47"><a href="#cb76-47" tabindex="-1"></a>              <span class="at">P2POINTCNT =</span> <span class="fu">first</span>(P2POINTCNT),</span>
<span id="cb76-48"><a href="#cb76-48" tabindex="-1"></a>              <span class="at">AREA_USED =</span> <span class="fu">first</span>(AREA_USED),</span>
<span id="cb76-49"><a href="#cb76-49" tabindex="-1"></a>              <span class="co"># Strata weight, relative to estimation unit</span></span>
<span id="cb76-50"><a href="#cb76-50" tabindex="-1"></a>              <span class="at">w =</span> <span class="fu">first</span>(P1POINTCNT) <span class="sc">/</span> <span class="fu">first</span>(P1PNTCNT_EU),</span>
<span id="cb76-51"><a href="#cb76-51" tabindex="-1"></a>              <span class="co"># Strata level variances</span></span>
<span id="cb76-52"><a href="#cb76-52" tabindex="-1"></a>              <span class="at">aVar =</span> (<span class="fu">sum</span>(forArea<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> aStrat<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> </span>
<span id="cb76-53"><a href="#cb76-53" tabindex="-1"></a>                     (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb76-54"><a href="#cb76-54" tabindex="-1"></a>              <span class="at">bioVar =</span> (<span class="fu">sum</span>(bioPlot<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> bioStrat<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> </span>
<span id="cb76-55"><a href="#cb76-55" tabindex="-1"></a>                       (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb76-56"><a href="#cb76-56" tabindex="-1"></a>              <span class="at">carbVar =</span> (<span class="fu">sum</span>(carbPlot<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> carbStrat<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> </span>
<span id="cb76-57"><a href="#cb76-57" tabindex="-1"></a>                        (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb76-58"><a href="#cb76-58" tabindex="-1"></a>              <span class="co"># Strata level co-varainces</span></span>
<span id="cb76-59"><a href="#cb76-59" tabindex="-1"></a>              <span class="at">bioCV =</span> (<span class="fu">sum</span>(forArea<span class="sc">*</span>bioPlot) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> aStrat <span class="sc">*</span>bioStrat)) <span class="sc">/</span> </span>
<span id="cb76-60"><a href="#cb76-60" tabindex="-1"></a>                      (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)),</span>
<span id="cb76-61"><a href="#cb76-61" tabindex="-1"></a>              <span class="at">carbCV =</span> (<span class="fu">sum</span>(forArea<span class="sc">*</span>carbPlot) <span class="sc">-</span> <span class="fu">sum</span>(P2POINTCNT <span class="sc">*</span> aStrat <span class="sc">*</span>carbStrat)) <span class="sc">/</span> </span>
<span id="cb76-62"><a href="#cb76-62" tabindex="-1"></a>                       (P2POINTCNT <span class="sc">*</span> (P2POINTCNT<span class="dv">-1</span>)), </span>
<span id="cb76-63"><a href="#cb76-63" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb76-64"><a href="#cb76-64" tabindex="-1"></a></span>
<span id="cb76-65"><a href="#cb76-65" tabindex="-1"></a>  <span class="co"># Moving on to the estimation unit</span></span>
<span id="cb76-66"><a href="#cb76-66" tabindex="-1"></a>  bio_pop_eu <span class="ot">&lt;-</span> bio_pop_strat <span class="sc">%&gt;%</span></span>
<span id="cb76-67"><a href="#cb76-67" tabindex="-1"></a>    <span class="fu">group_by</span>(ESTN_UNIT_CN) <span class="sc">%&gt;%</span></span>
<span id="cb76-68"><a href="#cb76-68" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">aEst =</span> <span class="fu">sum</span>(aStrat <span class="sc">*</span> w, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">first</span>(AREA_USED), <span class="co"># Mean Area</span></span>
<span id="cb76-69"><a href="#cb76-69" tabindex="-1"></a>              <span class="at">bioEst =</span> <span class="fu">sum</span>(bioStrat <span class="sc">*</span> w, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">first</span>(AREA_USED), <span class="co"># Mean biomass</span></span>
<span id="cb76-70"><a href="#cb76-70" tabindex="-1"></a>              <span class="at">carbEst =</span> <span class="fu">sum</span>(carbStrat <span class="sc">*</span> w, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="fu">first</span>(AREA_USED), <span class="co"># Mean carbon</span></span>
<span id="cb76-71"><a href="#cb76-71" tabindex="-1"></a>              <span class="co"># Estimation unit variances</span></span>
<span id="cb76-72"><a href="#cb76-72" tabindex="-1"></a>              <span class="at">aVar =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb76-73"><a href="#cb76-73" tabindex="-1"></a>                (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>aVar) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>aVar)),</span>
<span id="cb76-74"><a href="#cb76-74" tabindex="-1"></a>              <span class="at">bioVar =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb76-75"><a href="#cb76-75" tabindex="-1"></a>                (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>bioVar) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>bioVar)),</span>
<span id="cb76-76"><a href="#cb76-76" tabindex="-1"></a>              <span class="at">carbVar =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb76-77"><a href="#cb76-77" tabindex="-1"></a>                (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>carbVar) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>carbVar)),</span>
<span id="cb76-78"><a href="#cb76-78" tabindex="-1"></a>              <span class="do">## Estimation unit covariances</span></span>
<span id="cb76-79"><a href="#cb76-79" tabindex="-1"></a>              <span class="at">bioCV =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb76-80"><a href="#cb76-80" tabindex="-1"></a>                (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>bioCV) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>bioCV)),</span>
<span id="cb76-81"><a href="#cb76-81" tabindex="-1"></a>              <span class="at">carbCV =</span> (<span class="fu">first</span>(AREA_USED)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(P2POINTCNT)) <span class="sc">*</span></span>
<span id="cb76-82"><a href="#cb76-82" tabindex="-1"></a>                (<span class="fu">sum</span>(P2POINTCNT<span class="sc">*</span>w<span class="sc">*</span>carbCV) <span class="sc">+</span> <span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>w)<span class="sc">*</span>(P2POINTCNT<span class="sc">/</span><span class="fu">sum</span>(P2POINTCNT))<span class="sc">*</span>carbCV)), </span>
<span id="cb76-83"><a href="#cb76-83" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb76-84"><a href="#cb76-84" tabindex="-1"></a></span>
<span id="cb76-85"><a href="#cb76-85" tabindex="-1"></a>  <span class="co"># Finally, sum across Estimation Units for totals</span></span>
<span id="cb76-86"><a href="#cb76-86" tabindex="-1"></a>  bio_pop_total <span class="ot">&lt;-</span> bio_pop_eu <span class="sc">%&gt;%</span></span>
<span id="cb76-87"><a href="#cb76-87" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">AREA_TOTAL =</span> <span class="fu">sum</span>(aEst, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-88"><a href="#cb76-88" tabindex="-1"></a>              <span class="at">BIO_AG_TOTAL =</span> <span class="fu">sum</span>(bioEst, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-89"><a href="#cb76-89" tabindex="-1"></a>              <span class="at">CARB_AG_TOTAL =</span> <span class="fu">sum</span>(carbEst, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb76-90"><a href="#cb76-90" tabindex="-1"></a>              <span class="co"># Ratios</span></span>
<span id="cb76-91"><a href="#cb76-91" tabindex="-1"></a>              <span class="at">BIO_AG_ACRE =</span> BIO_AG_TOTAL <span class="sc">/</span> AREA_TOTAL,</span>
<span id="cb76-92"><a href="#cb76-92" tabindex="-1"></a>              <span class="at">CARB_AG_ACRE =</span> CARB_AG_TOTAL <span class="sc">/</span> AREA_TOTAL,</span>
<span id="cb76-93"><a href="#cb76-93" tabindex="-1"></a>              <span class="co"># Total samping errors</span></span>
<span id="cb76-94"><a href="#cb76-94" tabindex="-1"></a>              <span class="at">AREA_TOTAL_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(aVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> AREA_TOTAL <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb76-95"><a href="#cb76-95" tabindex="-1"></a>              <span class="at">BIO_AG_TOTAL_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(bioVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> BIO_AG_TOTAL <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb76-96"><a href="#cb76-96" tabindex="-1"></a>              <span class="at">CARB_AG_TOTAL_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(carbVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> CARB_AG_TOTAL <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb76-97"><a href="#cb76-97" tabindex="-1"></a>              <span class="co"># Ratio variances</span></span>
<span id="cb76-98"><a href="#cb76-98" tabindex="-1"></a>              <span class="at">bioAcreVar =</span> (<span class="dv">1</span> <span class="sc">/</span> AREA_TOTAL<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> (<span class="fu">sum</span>(bioVar) <span class="sc">+</span> </span>
<span id="cb76-99"><a href="#cb76-99" tabindex="-1"></a>                           (BIO_AG_ACRE<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sum</span>(aVar) <span class="sc">-</span></span>
<span id="cb76-100"><a href="#cb76-100" tabindex="-1"></a>                           <span class="dv">2</span> <span class="sc">*</span> BIO_AG_ACRE <span class="sc">*</span> <span class="fu">sum</span>(bioCV)),</span>
<span id="cb76-101"><a href="#cb76-101" tabindex="-1"></a>              <span class="at">carbAcreVar =</span> (<span class="dv">1</span> <span class="sc">/</span> AREA_TOTAL<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> (<span class="fu">sum</span>(carbVar) <span class="sc">+</span> </span>
<span id="cb76-102"><a href="#cb76-102" tabindex="-1"></a>                            (CARB_AG_ACRE<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span><span class="fu">sum</span>(aVar) <span class="sc">-</span>  </span>
<span id="cb76-103"><a href="#cb76-103" tabindex="-1"></a>                            <span class="dv">2</span> <span class="sc">*</span> CARB_AG_ACRE <span class="sc">*</span> <span class="fu">sum</span>(carbCV)),</span>
<span id="cb76-104"><a href="#cb76-104" tabindex="-1"></a>              <span class="at">BIO_AG_ACRE_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(bioAcreVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> </span>
<span id="cb76-105"><a href="#cb76-105" tabindex="-1"></a>                               BIO_AG_ACRE <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb76-106"><a href="#cb76-106" tabindex="-1"></a>              <span class="at">CARB_AG_ACRE_SE =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(carbAcreVar, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> </span>
<span id="cb76-107"><a href="#cb76-107" tabindex="-1"></a>                                CARB_AG_ACRE <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb76-108"><a href="#cb76-108" tabindex="-1"></a>    <span class="co"># Re ordering, dropping variance</span></span>
<span id="cb76-109"><a href="#cb76-109" tabindex="-1"></a>    <span class="fu">select</span>(BIO_AG_ACRE, CARB_AG_ACRE, BIO_AG_TOTAL, CARB_AG_TOTAL, </span>
<span id="cb76-110"><a href="#cb76-110" tabindex="-1"></a>           AREA_TOTAL, BIO_AG_ACRE_SE, CARB_AG_ACRE_SE, BIO_AG_TOTAL_SE, </span>
<span id="cb76-111"><a href="#cb76-111" tabindex="-1"></a>           CARB_AG_TOTAL_SE, AREA_TOTAL_SE)</span>
<span id="cb76-112"><a href="#cb76-112" tabindex="-1"></a></span>
<span id="cb76-113"><a href="#cb76-113" tabindex="-1"></a>  <span class="co"># Saving the output in our list...</span></span>
<span id="cb76-114"><a href="#cb76-114" tabindex="-1"></a>  bio_pop[[i]] <span class="ot">&lt;-</span> bio_pop_total</span>
<span id="cb76-115"><a href="#cb76-115" tabindex="-1"></a>}</span></code></pre></div>
<p>Great, we have our estimates! Except they are locked up in a list.
Let’s convert back to a <code>data.frame</code> and rejoining with
<code>grps</code>:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a>bio_pop <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(bio_pop)</span>
<span id="cb77-2"><a href="#cb77-2" tabindex="-1"></a>bio_pop_sp <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(grps, bio_pop)</span></code></pre></div>
<p>Comparing with rFIA, we have a match!</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" tabindex="-1"></a><span class="fu">glimpse</span>(<span class="fu">biomass</span>(<span class="fu">clipFIA</span>(fiaRI), <span class="at">totals =</span> <span class="cn">TRUE</span>, <span class="at">bySpecies =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## Rows: 45
## Columns: 17
## $ YEAR            &lt;dbl&gt; 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, …
## $ SPCD            &lt;dbl&gt; 12, 43, 68, 126, 129, 130, 261, 313, 316, 317, 318, 32…
## $ COMMON_NAME     &lt;chr&gt; &quot;balsam fir&quot;, &quot;Atlantic white-cedar&quot;, &quot;eastern redceda…
## $ SCIENTIFIC_NAME &lt;chr&gt; &quot;Abies balsamea&quot;, &quot;Chamaecyparis thyoides&quot;, &quot;Juniperus…
## $ BIO_ACRE        &lt;dbl&gt; 9.019379e-03, 4.327762e-02, 4.191399e-02, 1.665285e+00…
## $ CARB_ACRE       &lt;dbl&gt; 0.0045638059, 0.0205568687, 0.0218371876, 0.7943407536…
## $ BIO_TOTAL       &lt;dbl&gt; 3309.7397, 15881.0985, 15380.7024, 611090.6699, 378204…
## $ CARB_TOTAL      &lt;dbl&gt; 1674.7283, 7543.5218, 8013.3459, 291490.2495, 1917499.…
## $ AREA_TOTAL      &lt;dbl&gt; 366958.7, 366958.7, 366958.7, 366958.7, 366958.7, 3669…
## $ BIO_ACRE_SE     &lt;dbl&gt; 114.028966, 56.662929, 68.992421, 49.802399, 18.886660…
## $ CARB_ACRE_SE    &lt;dbl&gt; 114.028966, 56.662929, 68.992421, 49.802399, 18.886660…
## $ BIO_TOTAL_SE    &lt;dbl&gt; 114.043537, 56.722024, 68.649804, 50.248846, 19.200896…
## $ CARB_TOTAL_SE   &lt;dbl&gt; 114.043537, 56.722024, 68.649804, 50.248846, 19.200896…
## $ AREA_TOTAL_SE   &lt;dbl&gt; 3.531998, 3.531998, 3.531998, 3.531998, 3.531998, 3.53…
## $ nPlots_TREE     &lt;int&gt; 1, 3, 5, 10, 63, 1, 8, 1, 107, 1, 8, 1, 22, 40, 1, 8, …
## $ nPlots_AREA     &lt;int&gt; 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127,…
## $ N               &lt;int&gt; 167, 199, 199, 199, 199, 167, 167, 167, 199, 167, 199,…</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a><span class="fu">glimpse</span>(bio_pop_sp)</span></code></pre></div>
<pre><code>## Rows: 50
## Columns: 12
## Groups: YEAR [1]
## $ YEAR             &lt;dbl&gt; 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018,…
## $ SPCD             &lt;dbl&gt; 12, 43, 68, 96, 126, 129, 130, 261, 313, 316, 317, 31…
## $ BIO_AG_ACRE      &lt;dbl&gt; 9.019379e-03, 4.327762e-02, 4.191399e-02, 0.000000e+0…
## $ CARB_AG_ACRE     &lt;dbl&gt; 0.0045638059, 0.0205568687, 0.0218371875, 0.000000000…
## $ BIO_AG_TOTAL     &lt;dbl&gt; 3309.7397, 15881.0985, 15380.7024, 0.0000, 611090.669…
## $ CARB_AG_TOTAL    &lt;dbl&gt; 1674.7283, 7543.5218, 8013.3459, 0.0000, 291490.2495,…
## $ AREA_TOTAL       &lt;dbl&gt; 366958.7, 366958.7, 366958.7, 366958.7, 366958.7, 366…
## $ BIO_AG_ACRE_SE   &lt;dbl&gt; 114.028966, 56.662929, 68.992421, NaN, 49.802399, 18.…
## $ CARB_AG_ACRE_SE  &lt;dbl&gt; 114.028966, 56.662929, 68.992421, NaN, 49.802399, 18.…
## $ BIO_AG_TOTAL_SE  &lt;dbl&gt; 114.043537, 56.722024, 68.649804, NaN, 50.248846, 19.…
## $ CARB_AG_TOTAL_SE &lt;dbl&gt; 114.043537, 56.722024, 68.649804, NaN, 50.248846, 19.…
## $ AREA_TOTAL_SE    &lt;dbl&gt; 3.531998, 3.531998, 3.531998, 3.531998, 3.531998, 3.5…</code></pre>
</div>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
