"""Generate ``src/pyfia/constants/fiadb_schema.py`` from a FIADB SQLite export.

FIA DataMart publishes each state's FIADB as a SQLite database whose table
definitions declare a type for every column. The smallest one covers every
table: download https://apps.fs.usda.gov/fia/datamart/Databases/SQLite_FIADB_AS.zip,
unzip it, and pass the ``.db`` file. ``tests/unit/test_fiadb_schema.py`` checks
the generated module's rules.

Declared types map to DuckDB types:

- ``VARCHAR(n)`` -> VARCHAR, ``INTEGER`` -> BIGINT, ``FLOAT`` -> DOUBLE,
  ``DATETIME`` -> TIMESTAMP.
- Every CN column (``CN`` or ``*_CN``) is VARCHAR, as the FIADB User Guide
  defines it. Some CNs have 23 digits, which no integer type holds.
- A FLOAT code or key column is BIGINT when a column of the same name is
  INTEGER in another table, so it joins that column (``TREE.SPCD`` to
  ``REF_SPECIES.SPCD``, ``PLOTGEOM.STATECD`` to ``PLOT.STATECD``). Code and
  key columns are those named ``*CD``, ``PLOT``, ``SUBP``, ``INVYR`` or
  ``ATTRIBUTE_NBR``; ``STDORGSP`` is a species code too. Measurements keep
  their declared FLOAT.

Usage::

    uv run python scripts/gen_fiadb_schema.py /path/to/SQLite_FIADB_AS.db
"""

from __future__ import annotations

import re
import sqlite3
import subprocess
import sys
from pathlib import Path

OUT = Path(__file__).parents[1] / "src" / "pyfia" / "constants" / "fiadb_schema.py"

DECLARED_TO_DUCKDB = {
    "VARCHAR": "VARCHAR",
    "INTEGER": "BIGINT",
    "FLOAT": "DOUBLE",
    "DATETIME": "TIMESTAMP",
}

# Key columns whose names don't end in CD.
KEY_COLUMNS = {"PLOT", "SUBP", "INVYR", "ATTRIBUTE_NBR"}

# Species codes whose column name differs from SPCD.
SPECIES_CODE_COLUMNS = {"STDORGSP"}


def _is_code_or_key(col: str) -> bool:
    return col.endswith("CD") or col in KEY_COLUMNS


TEMPLATE = '''"""
FIADB column types from the table definitions of the FIA DataMart SQLite export.

Generated by ``scripts/gen_fiadb_schema.py`` from {version}; regenerate rather
than editing by hand. Types are DuckDB types (VARCHAR, BIGINT, DOUBLE,
TIMESTAMP). CN columns are VARCHAR, and FLOAT-declared code and key columns
that join an INTEGER column of the same name are BIGINT; the script's
docstring gives the rules.
"""

from __future__ import annotations

FIADB_VERSION = "{version}"

# table -> column -> DuckDB type, in the export's column order
COLUMN_TYPES: dict[str, dict[str, str]] = {{
{tables}
}}
'''


def _declared(con: sqlite3.Connection) -> dict[str, list[tuple[str, str]]]:
    tables = [
        r[0]
        for r in con.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name"
        )
    ]
    out: dict[str, list[tuple[str, str]]] = {}
    for table in tables:
        cols = con.execute(f'PRAGMA table_info("{table}")').fetchall()
        out[table] = [(c[1], re.sub(r"\(.*\)", "", c[2]).strip().upper()) for c in cols]
    return out


def column_types(
    declared: dict[str, list[tuple[str, str]]],
) -> dict[str, dict[str, str]]:
    """Apply the module docstring's rules to the declared types."""
    integer_names = {
        col for cols in declared.values() for col, typ in cols if typ == "INTEGER"
    }
    result: dict[str, dict[str, str]] = {}
    for table, cols in declared.items():
        types: dict[str, str] = {}
        for col, typ in cols:
            if typ not in DECLARED_TO_DUCKDB:
                raise ValueError(f"{table}.{col}: unexpected declared type {typ!r}")
            if col == "CN" or col.endswith("_CN"):
                types[col] = "VARCHAR"
            elif typ == "FLOAT" and (
                (_is_code_or_key(col) and col in integer_names)
                or col in SPECIES_CODE_COLUMNS
            ):
                types[col] = "BIGINT"
            else:
                types[col] = DECLARED_TO_DUCKDB[typ]
        result[table] = types
    return result


def main(src: str) -> None:
    with sqlite3.connect(f"file:{src}?mode=ro", uri=True) as con:
        declared = _declared(con)
        version = con.execute(
            "SELECT VERSION FROM REF_FIADB_VERSION ORDER BY CREATED_DATE DESC LIMIT 1"
        ).fetchone()[0]

    types = column_types(declared)
    blocks = []
    for table, cols in types.items():
        body = "\n".join(f'        "{c}": "{t}",' for c, t in cols.items())
        blocks.append(f'    "{table}": {{\n{body}\n    }},')
    OUT.write_text(TEMPLATE.format(version=version, tables="\n".join(blocks)))
    subprocess.run(["ruff", "format", str(OUT)], check=True)

    promoted = sorted(
        f"{t}.{c}"
        for t, cols in declared.items()
        for c, typ in cols
        if typ == "FLOAT" and types[t][c] == "BIGINT"
    )
    n_cols = sum(len(c) for c in types.values())
    print(f"Wrote {OUT}: {len(types)} tables, {n_cols} columns, {version}")
    print(f"FLOAT columns stored as BIGINT ({len(promoted)}): {', '.join(promoted)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
