"""Generate ``src/pyfia/constants/forest_types.py`` from FIADB REF tables.

Reads ``REF_FOREST_TYPE`` (FORTYPCD -> TYPGRPCD) and ``REF_FOREST_TYPE_GROUP``
(TYPGRPCD -> name) from any state's FIADB DuckDB; both are national tables.
``tests/unit/test_forest_type_groups.py`` checks the generated module against
the REF tables in the test fixture.

Usage::

    uv run python scripts/gen_forest_type_groups.py /path/to/ST.duckdb
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import duckdb

OUT = Path(__file__).parents[1] / "src" / "pyfia" / "constants" / "forest_types.py"

TEMPLATE = '''"""
Forest type groups from FIADB ``REF_FOREST_TYPE`` and ``REF_FOREST_TYPE_GROUP``.

Generated by ``scripts/gen_forest_type_groups.py`` from {version}; regenerate
rather than editing by hand. ``tests/unit/test_forest_type_groups.py`` checks
these mappings against the REF tables.
"""

from __future__ import annotations

FIADB_VERSION = "{version}"

# REF_FOREST_TYPE: FORTYPCD -> TYPGRPCD
FOREST_TYPE_GROUP_CODES: dict[int, int] = {{
{codes}
}}

# REF_FOREST_TYPE_GROUP: TYPGRPCD -> MEANING
FOREST_TYPE_GROUP_NAMES: dict[int, str] = {{
{names}
}}
'''


def main(src: str) -> None:
    with duckdb.connect(src, read_only=True) as con:
        codes = con.execute(
            "SELECT VALUE, TYPGRPCD FROM REF_FOREST_TYPE ORDER BY VALUE"
        ).fetchall()
        names = con.execute(
            "SELECT VALUE, MEANING FROM REF_FOREST_TYPE_GROUP ORDER BY VALUE"
        ).fetchall()
        version = con.execute(
            "SELECT VERSION FROM REF_FIADB_VERSION ORDER BY CREATED_DATE DESC LIMIT 1"
        ).fetchone()

    OUT.write_text(
        TEMPLATE.format(
            version=version[0] if version else "unknown",
            codes="\n".join(f"    {int(v)}: {int(g)}," for v, g in codes),
            names="\n".join(f"    {int(v)}: {m!r}," for v, m in names),
        )
    )
    subprocess.run(["ruff", "format", str(OUT)], check=True)
    print(f"{len(codes)} forest types, {len(names)} groups -> {OUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
