name: Coverage Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e .[dev]
    
    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        uv run pytest --cov=pyfia --cov-report=term-missing --cov-report=html
    
    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30
    
    - name: Coverage comment
      run: |
        echo "## 📊 Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Coverage HTML report has been uploaded as an artifact." >> $GITHUB_STEP_SUMMARY
        echo "Download it from the Actions tab to view detailed coverage." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Summary:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        source .venv/bin/activate
        uv run pytest --cov=pyfia --cov-report=term-missing --tb=no -q | grep -E "(TOTAL|Name)" || true
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY 