name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .[dev]
    
    - name: Run linting
      run: |
        uv run ruff check pyfia/ tests/
        uv run ruff format --check pyfia/ tests/
    
    - name: Run type checking
      run: uv run mypy pyfia/
    
    - name: Run tests
      run: uv run pytest tests/ -v
    
    - name: Test CLI commands
      run: |
        uv run pyfia --help
        uv run pyfia-ai --help 